running
setUp
	nala := Mamifero new.
	nala identificador: 'Nala'.
	melquiades := Mamifero new.
	melquiades identificador: 'Melquiades'.
	mufasa := Mamifero new.
	mufasa identificador: 'Mufasa'.
	alexa := Mamifero new.
	alexa identificador: 'Alexa'.
	elsa := Mamifero new.
	elsa identificador: 'Elsa'.
	scar := Mamifero new.
	scar identificador: 'Scar'.
	sarabi := Mamifero new.
	sarabi identificador: 'Sarabi'.
	anonimo := Mamifero new.
	alexa padre: mufasa.
	alexa madre: sarabi.
	mufasa padre: melquiades.
	mufasa madre: nala.
	sarabi padre: scar.
	sarabi madre: elsa